### ISSUE TITLE
allow multiple netshare options in same /etc/default file

### ISSUE THREAD

**Issue by pimpim** [gondor/docker-volume-netshare#3]
Would there be a way to allow multiple options in the same /etc/default file to start multiple plugins using the same service? It would look something like:

DKV_NETSHARE_OPTS="nfs; cifs -u user -p pass -d domain; cifs -u user2 -p pass2 - d domain2"

**Comment by gondor** [comment]
I'm almost leaning towards keeping this as is but the ability to specify a config file.  The config file would be hierarchically structures JSON or YAML and would allow you to declare volumes by name along with credential sets, etc.  

This would also allow you to run a single netshare daemon in multi mode where you can mount any of the supported filesystems since the volumes would of been declared in the config file.

**Proposal**

Just an example config:
```
{
  "volumes": {
     "vol1" : { "type": "cifs", "auth": "serverA" },
     "otherVol" : { "type": "nfs" }
  },
  "authentication" : {
     "serverA" : { "user": "john", "password": "pass", "domain": "mydomain" }
  }
}
```
Example running the daemon:  
```
$ sudo docker-volume-netshare multi --config /etc/netshareconf.json
```
Example launching Docker
```
$ docker run -i -t --rm --volume-driver=netshare -v vol1/path:/data/vol1 -v otherVol/dir:/data/other ubuntu /bin/bash
``` 

In multi mode the volume servers would need to be pre-declared but you would be able to mount multiple technologies.   

This has been a limitation in the current Docker daemon implementation and the above would get around that if you felt this was a good path to go down.

**Comment by pimpim** [comment]
sounds like a good idea!
I don't really know if this is different, but in rbd-docker-plugin you can start multiple plugins simultaneously by using different names:

sudo rbd-docker-plugin --name rbd2 --pool liverpool
sudo rbd-docker-plugin --name otherrdb --pool swimmingpool
docker run --volume-driver rbd2 -v myvol2:/mnt/a --volume-driver otherrdb -v sharedvol4:/other ...

https://github.com/yp-engineering/rbd-docker-plugin

**Comment by gondor** [comment]
What your describing above would be easy to allow an adhoc name during launch but it doesn't solve the original context of this issue when combining the /etc/default and a service unless I'm missing something?

**Comment by gondor** [comment]
Re-open if more feedback is needed.
